swagger: "2.0"
info:
  title: traveloka-cloud-run
  description: Traveloka Cloud Run API Gateway
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
security:
  - firebase: []
paths:
  /:
    get:
      summary: Traveloka Hotel Ranking API
      operationId: traveloka-home
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app
      responses:
        "200":
          description: OK
  /users:
    get:
      summary: Traveloka Hotel Ranking Get all Users
      operationId: traveloka-getAllUsers
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app/users
      responses:
        "200":
          description: OK
    post:
      summary: Traveloka Hotel Ranking Add new user
      operationId: "addUser"
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app/users
      responses:
        "200":
          description: OK
        "400":
          description: "Missing required fields"
  /users/{id}:
    get:
      summary: Traveloka Hotel Ranking Get all Users
      operationId: traveloka-getUser
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid ID User"
        "404":
          description: "User not found"
    put:
      summary: Traveloka Hotel Ranking Update User
      operationId: "traveloka-updateUser"
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid user validation"
        "404":
          description: "User not found"
    delete:
      summary: Traveloka Hotel Ranking Delete User
      operationId: "traveloka-deleteUser"
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid ID User"
        "404":
          description: "User not found"
  /users/reviews:
    get:
      summary: Traveloka Hotel Ranking Get all Users Reviews
      operationId: traveloka-getAllReviewsUsers
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app/users/reviews
      responses:
        "200":
          description: OK
  /users/{id}/reviews:
    get:
      summary: Traveloka Hotel Ranking Get User Review by user ID
      operationId: traveloka-getAllReviewByUserId
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid ID User"
        "404":
          description: "User not found"
  /hotels:
    get:
      summary: Traveloka Hotel Ranking Get all Hotels
      operationId: traveloka-getAllHotels
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app/hotels
      responses:
        "200":
          description: OK
  /hotels/{id}:
    get:
      summary: Traveloka Hotel Ranking Get Hotel by ID
      operationId: traveloka-getHotelById
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid ID Hotel"
        "404":
          description: "Hotel not found"
  /hotels/{id}/reviews:
    get:
      summary: Traveloka Hotel Ranking Get Hotel Review by ID Hotel
      operationId: traveloka-getHotelReviewsByIdHotel
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid ID Hotel"
        "404":
          description: "Hotel not found"
  /hotels/reviews:
    get:
      summary: Traveloka Hotel Ranking Get All Hotels and Reviews
      operationId: traveloka-getAllHotelsAndReviews
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app/hotels/reviews
      responses:
        "200":
          description: OK
  /reviews:
    post:
      summary: Traveloka Hotel Ranking Add new Review
      operationId: traveloka-addNewReview
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app/reviews
      responses:
        "200":
          description: OK
        "400":
          description: "Missing required fields"
    get:
      summary: Traveloka Hotel Ranking Get All Reviews
      operationId: traveloka-getAllReviews
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app/reviews
      responses:
        "200":
          description: OK
  /reviews/{id}:
    get:
      summary: Traveloka Hotel Ranking Get Review by ID
      operationId: traveloka-getReviewById
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid ID Review"
        "404":
          description: "Review not found"
    delete:
      summary: Traveloka Hotel Ranking Delete User
      operationId: "traveloka-deleteReview"
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid ID Review"
        "404":
          description: "Review not found"
    put:
      summary: Traveloka Hotel Ranking Update Review
      operationId: "traveloka-updateReview"
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid ID Review"
        "404":
          description: "Review not found"
securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/traveloka-hotel-opt"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "traveloka-hotel-opt"
