swagger: "2.0"
info:
  title: traveloka-cloud-run
  description: Traveloka Cloud Run API Gateway
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
security:
  - api_key: []
paths:
  /:
    get:
      summary: Traveloka Hotel Ranking API
      operationId: traveloka-home
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app/
      responses:
        "200":
          description: OK
  /users:
    get:
      tags:
        - "User"
      summary: Traveloka Hotel Ranking Get all Users
      operationId: traveloka-getAllUsers
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app/users
      responses:
        "200":
          description: OK
    post:
      tags:
        - "User"
      summary: Traveloka Hotel Ranking Add new user
      operationId: "addUser"
      responses:
        "200":
          description: OK
        "400":
          description: "Missing required fields"
  /users/{id}:
    get:
      tags:
        - "User"
      summary: Traveloka Hotel Ranking Get all Users
      operationId: traveloka-getUser
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          maximum: 10.0
          minimum: 1.0
          format: "int64"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Invalid ID User"
        "404":
          description: "User not found"
    put:
      tags:
        - "User"
      summary: Traveloka Hotel Ranking Update User
      operationId: "traveloka-updateUser"
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid user validation"
        "404":
          description: "User not found"
    delete:
      tags:
        - "User"
      summary: Traveloka Hotel Ranking Delete User
      operationId: "traveloka-deleteUser"
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid ID User"
        "404":
          description: "User not found"
  /users/reviews:
    get:
      tags:
        - "User"
      summary: Traveloka Hotel Ranking Get all Users Reviews
      operationId: traveloka-getAllReviewsUsers
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app/users/reviews
      responses:
        "200":
          description: OK
  /users/{id}/reviews:
    get:
      tags:
        - "User"
      summary: Traveloka Hotel Ranking Get User Review by user ID
      operationId: traveloka-getAllReviewByUserId
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app/users/reviews
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid ID User"
        "404":
          description: "User not found"
  /hotels:
    get:
      tags:
        - "Hotel"
      summary: Traveloka Hotel Ranking Get all Hotels
      operationId: traveloka-getAllHotels
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app/hotels
      responses:
        "200":
          description: OK
  /hotels/{id}:
    get:
      tags:
        - "Hotel"
      summary: Traveloka Hotel Ranking Get Hotel by ID
      operationId: traveloka-getHotelById
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/Hotel"
        "400":
          description: "Invalid ID Hotel"
        "404":
          description: "Hotel not found"
  /hotels/{id}/reviews:
    get:
      tags:
        - "Hotel"
      summary: Traveloka Hotel Ranking Get Hotel Review by ID Hotel
      operationId: traveloka-getHotelReviewsByIdHotel
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS\
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid ID Hotel"
        "404":
          description: "Hotel not found"
  /hotels/reviews:
    get:
      tags:
        - "Hotel"
      summary: Traveloka Hotel Ranking Get All Hotels and Reviews
      operationId: traveloka-getAllHotelsAndReviews
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app/hotels/reviews
      responses:
        "200":
          description: OK
  /reviews:
    post:
      tags:
        - "Review"
      summary: Traveloka Hotel Ranking Add new Review
      operationId: traveloka-addNewReview
      responses:
        "200":
          description: OK
        "400":
          description: "Missing required fields"
    get:
      tags:
        - "Review"
      summary: Traveloka Hotel Ranking Get All Reviews
      operationId: traveloka-getAllReviews
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app/reviews
      responses:
        "200":
          description: OK
  /reviews/{id}:
    get:
      tags:
        - "Review"
      summary: Traveloka Hotel Ranking Get Review by ID
      operationId: traveloka-getReviewById
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/Review"
        "400":
          description: "Invalid ID Review"
        "404":
          description: "Review not found"
    delete:
      tags:
        - "Review"
      summary: Traveloka Hotel Ranking Delete User
      operationId: "traveloka-deleteReview"
      x-google-backend:
        address: https://traveloka-hotel-bbfcamhapq-as.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid ID Review"
        "404":
          description: "Review not found"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
definitions:
  User:
    type: "object"
    properties:
      name:
        type: "string"
      email:
        type: "string"
      phone:
        type: "string"
    xml:
      name: "User"
  Hotel:
    type: "object"
    properties:
      name:
        type: "string"
      addres:
        type: "string"
      image:
        type: "string"
      description:
        type: "string"
    xml:
      name: "Hotel"
  Review:
    type: "object"
    properties:
      rating:
        type: "string"
      comment:
        type: "string"
    xml:
      name: "Review"
